In [1]:
import pandas as pd

In [47]:
dataset_url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo = pd.read_csv(dataset_url, sep='\t')

In [48]:
price = [float(value[1: -1]) for value in chipo.item_price]
chipo.item_price = price
chipo_filtered = chipo.drop_duplicates(['item_name', 'quantity', 'choice_description'])
chipo_filtered = chipo_filtered[chipo_filtered.quantity == 1]
chipo_filtered.head(5)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>order_id</th>
      <th>quantity</th>
      <th>item_name</th>
      <th>choice_description</th>
      <th>item_price</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>1</td>
      <td>Chips and Fresh Tomato Salsa</td>
      <td>NaN</td>
      <td>2.39</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1</td>
      <td>1</td>
      <td>Izze</td>
      <td>[Clementine]</td>
      <td>3.39</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1</td>
      <td>1</td>
      <td>Nantucket Nectar</td>
      <td>[Apple]</td>
      <td>3.39</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1</td>
      <td>1</td>
      <td>Chips and Tomatillo-Green Chili Salsa</td>
      <td>NaN</td>
      <td>2.39</td>
    </tr>
    <tr>
      <th>5</th>
      <td>3</td>
      <td>1</td>
      <td>Chicken Bowl</td>
      <td>[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...</td>
      <td>10.98</td>
    </tr>
  </tbody>
</table>
</div>

In [50]:
chipo_filtered = chipo_filtered.drop_duplicates(['item_name'])
chipo_filtered = chipo_filtered[['item_name', 'item_price']]
chipo_filtered = chipo_filtered.sort_values(by='item_price', ascending=False)
chipo_filtered

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>item_name</th>
      <th>item_price</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>606</th>
      <td>Steak Salad Bowl</td>
      <td>11.89</td>
    </tr>
    <tr>
      <th>1229</th>
      <td>Barbacoa Salad Bowl</td>
      <td>11.89</td>
    </tr>
    <tr>
      <th>1132</th>
      <td>Carnitas Salad Bowl</td>
      <td>11.89</td>
    </tr>
    <tr>
      <th>7</th>
      <td>Steak Burrito</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>168</th>
      <td>Barbacoa Crispy Tacos</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>39</th>
      <td>Barbacoa Bowl</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>738</th>
      <td>Veggie Soft Tacos</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>186</th>
      <td>Veggie Salad Bowl</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>62</th>
      <td>Veggie Bowl</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>57</th>
      <td>Veggie Burrito</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>250</th>
      <td>Chicken Salad</td>
      <td>10.98</td>
    </tr>
    <tr>
      <th>5</th>
      <td>Chicken Bowl</td>
      <td>10.98</td>
    </tr>
    <tr>
      <th>8</th>
      <td>Steak Soft Tacos</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>554</th>
      <td>Carnitas Crispy Tacos</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>237</th>
      <td>Carnitas Soft Tacos</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>56</th>
      <td>Barbacoa Soft Tacos</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>92</th>
      <td>Steak Crispy Tacos</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>664</th>
      <td>Steak Salad</td>
      <td>8.99</td>
    </tr>
    <tr>
      <th>54</th>
      <td>Steak Bowl</td>
      <td>8.99</td>
    </tr>
    <tr>
      <th>3750</th>
      <td>Carnitas Salad</td>
      <td>8.99</td>
    </tr>
    <tr>
      <th>21</th>
      <td>Barbacoa Burrito</td>
      <td>8.99</td>
    </tr>
    <tr>
      <th>27</th>
      <td>Carnitas Burrito</td>
      <td>8.99</td>
    </tr>
    <tr>
      <th>33</th>
      <td>Carnitas Bowl</td>
      <td>8.99</td>
    </tr>
    <tr>
      <th>11</th>
      <td>Chicken Crispy Tacos</td>
      <td>8.75</td>
    </tr>
    <tr>
      <th>12</th>
      <td>Chicken Soft Tacos</td>
      <td>8.75</td>
    </tr>
    <tr>
      <th>44</th>
      <td>Chicken Salad Bowl</td>
      <td>8.75</td>
    </tr>
    <tr>
      <th>1653</th>
      <td>Veggie Crispy Tacos</td>
      <td>8.49</td>
    </tr>
    <tr>
      <th>16</th>
      <td>Chicken Burrito</td>
      <td>8.49</td>
    </tr>
    <tr>
      <th>1694</th>
      <td>Veggie Salad</td>
      <td>8.49</td>
    </tr>
    <tr>
      <th>1414</th>
      <td>Salad</td>
      <td>7.40</td>
    </tr>
    <tr>
      <th>510</th>
      <td>Burrito</td>
      <td>7.40</td>
    </tr>
    <tr>
      <th>520</th>
      <td>Crispy Tacos</td>
      <td>7.40</td>
    </tr>
    <tr>
      <th>673</th>
      <td>Bowl</td>
      <td>7.40</td>
    </tr>
    <tr>
      <th>298</th>
      <td>6 Pack Soft Drink</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>10</th>
      <td>Chips and Guacamole</td>
      <td>4.45</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Izze</td>
      <td>3.39</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Nantucket Nectar</td>
      <td>3.39</td>
    </tr>
    <tr>
      <th>674</th>
      <td>Chips and Mild Fresh Tomato Salsa</td>
      <td>3.00</td>
    </tr>
    <tr>
      <th>111</th>
      <td>Chips and Tomatillo Red Chili Salsa</td>
      <td>2.95</td>
    </tr>
    <tr>
      <th>233</th>
      <td>Chips and Roasted Chili Corn Salsa</td>
      <td>2.95</td>
    </tr>
    <tr>
      <th>38</th>
      <td>Chips and Tomatillo Green Chili Salsa</td>
      <td>2.95</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Chips and Tomatillo-Green Chili Salsa</td>
      <td>2.39</td>
    </tr>
    <tr>
      <th>300</th>
      <td>Chips and Tomatillo-Red Chili Salsa</td>
      <td>2.39</td>
    </tr>
    <tr>
      <th>191</th>
      <td>Chips and Roasted Chili-Corn Salsa</td>
      <td>2.39</td>
    </tr>
    <tr>
      <th>0</th>
      <td>Chips and Fresh Tomato Salsa</td>
      <td>2.39</td>
    </tr>
    <tr>
      <th>40</th>
      <td>Chips</td>
      <td>2.15</td>
    </tr>
    <tr>
      <th>6</th>
      <td>Side of Chips</td>
      <td>1.69</td>
    </tr>
    <tr>
      <th>263</th>
      <td>Canned Soft Drink</td>
      <td>1.25</td>
    </tr>
    <tr>
      <th>28</th>
      <td>Canned Soda</td>
      <td>1.09</td>
    </tr>
    <tr>
      <th>34</th>
      <td>Bottled Water</td>
      <td>1.09</td>
    </tr>
  </tbody>
</table>
</div>

In [54]:
chipo_shorted_by_name = chipo.sort_values(by='item_name', ascending=True)
chipo_shorted_by_name

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>order_id</th>
      <th>quantity</th>
      <th>item_name</th>
      <th>choice_description</th>
      <th>item_price</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>3389</th>
      <td>1360</td>
      <td>2</td>
      <td>6 Pack Soft Drink</td>
      <td>[Diet Coke]</td>
      <td>12.98</td>
    </tr>
    <tr>
      <th>341</th>
      <td>148</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Diet Coke]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>1849</th>
      <td>749</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Coke]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>1860</th>
      <td>754</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Diet Coke]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>2713</th>
      <td>1076</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Coke]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>3422</th>
      <td>1373</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Coke]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>553</th>
      <td>230</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Diet Coke]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>1916</th>
      <td>774</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Diet Coke]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>1922</th>
      <td>776</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Coke]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>1937</th>
      <td>784</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Diet Coke]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>3836</th>
      <td>1537</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Coke]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>298</th>
      <td>129</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Sprite]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>1976</th>
      <td>798</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Diet Coke]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>1167</th>
      <td>481</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Coke]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>3875</th>
      <td>1554</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Diet Coke]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>1124</th>
      <td>465</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Coke]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>3886</th>
      <td>1558</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Diet Coke]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>2108</th>
      <td>849</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Coke]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>3010</th>
      <td>1196</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Diet Coke]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>4535</th>
      <td>1803</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Lemonade]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>4169</th>
      <td>1664</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Diet Coke]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>4174</th>
      <td>1666</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Coke]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>4527</th>
      <td>1800</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Diet Coke]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>4522</th>
      <td>1798</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Diet Coke]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>3806</th>
      <td>1525</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Sprite]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>2389</th>
      <td>949</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Coke]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>3132</th>
      <td>1248</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Diet Coke]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>3141</th>
      <td>1253</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Lemonade]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>639</th>
      <td>264</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Diet Coke]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>1026</th>
      <td>422</td>
      <td>1</td>
      <td>6 Pack Soft Drink</td>
      <td>[Sprite]</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>2996</th>
      <td>1192</td>
      <td>1</td>
      <td>Veggie Salad</td>
      <td>[Roasted Chili Corn Salsa (Medium), [Black Bea...</td>
      <td>8.49</td>
    </tr>
    <tr>
      <th>3163</th>
      <td>1263</td>
      <td>1</td>
      <td>Veggie Salad</td>
      <td>[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...</td>
      <td>8.49</td>
    </tr>
    <tr>
      <th>4084</th>
      <td>1635</td>
      <td>1</td>
      <td>Veggie Salad</td>
      <td>[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...</td>
      <td>8.49</td>
    </tr>
    <tr>
      <th>1694</th>
      <td>686</td>
      <td>1</td>
      <td>Veggie Salad</td>
      <td>[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...</td>
      <td>8.49</td>
    </tr>
    <tr>
      <th>2756</th>
      <td>1094</td>
      <td>1</td>
      <td>Veggie Salad</td>
      <td>[[Tomatillo-Green Chili Salsa (Medium), Roaste...</td>
      <td>8.49</td>
    </tr>
    <tr>
      <th>4201</th>
      <td>1677</td>
      <td>1</td>
      <td>Veggie Salad Bowl</td>
      <td>[Fresh Tomato Salsa, [Fajita Vegetables, Black...</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>1884</th>
      <td>760</td>
      <td>1</td>
      <td>Veggie Salad Bowl</td>
      <td>[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>455</th>
      <td>195</td>
      <td>1</td>
      <td>Veggie Salad Bowl</td>
      <td>[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>3223</th>
      <td>1289</td>
      <td>1</td>
      <td>Veggie Salad Bowl</td>
      <td>[Tomatillo Red Chili Salsa, [Fajita Vegetables...</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>2223</th>
      <td>896</td>
      <td>1</td>
      <td>Veggie Salad Bowl</td>
      <td>[Roasted Chili Corn Salsa, Fajita Vegetables]</td>
      <td>8.75</td>
    </tr>
    <tr>
      <th>2269</th>
      <td>913</td>
      <td>1</td>
      <td>Veggie Salad Bowl</td>
      <td>[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...</td>
      <td>8.75</td>
    </tr>
    <tr>
      <th>4541</th>
      <td>1805</td>
      <td>1</td>
      <td>Veggie Salad Bowl</td>
      <td>[Tomatillo Green Chili Salsa, [Fajita Vegetabl...</td>
      <td>8.75</td>
    </tr>
    <tr>
      <th>3293</th>
      <td>1321</td>
      <td>1</td>
      <td>Veggie Salad Bowl</td>
      <td>[Fresh Tomato Salsa, [Rice, Black Beans, Chees...</td>
      <td>8.75</td>
    </tr>
    <tr>
      <th>186</th>
      <td>83</td>
      <td>1</td>
      <td>Veggie Salad Bowl</td>
      <td>[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>960</th>
      <td>394</td>
      <td>1</td>
      <td>Veggie Salad Bowl</td>
      <td>[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...</td>
      <td>8.75</td>
    </tr>
    <tr>
      <th>1316</th>
      <td>536</td>
      <td>1</td>
      <td>Veggie Salad Bowl</td>
      <td>[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...</td>
      <td>8.75</td>
    </tr>
    <tr>
      <th>2156</th>
      <td>869</td>
      <td>1</td>
      <td>Veggie Salad Bowl</td>
      <td>[Tomatillo Red Chili Salsa, [Fajita Vegetables...</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>4261</th>
      <td>1700</td>
      <td>1</td>
      <td>Veggie Salad Bowl</td>
      <td>[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>295</th>
      <td>128</td>
      <td>1</td>
      <td>Veggie Salad Bowl</td>
      <td>[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>4573</th>
      <td>1818</td>
      <td>1</td>
      <td>Veggie Salad Bowl</td>
      <td>[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...</td>
      <td>8.75</td>
    </tr>
    <tr>
      <th>2683</th>
      <td>1066</td>
      <td>1</td>
      <td>Veggie Salad Bowl</td>
      <td>[Roasted Chili Corn Salsa, [Fajita Vegetables,...</td>
      <td>8.75</td>
    </tr>
    <tr>
      <th>496</th>
      <td>207</td>
      <td>1</td>
      <td>Veggie Salad Bowl</td>
      <td>[Fresh Tomato Salsa, [Rice, Lettuce, Guacamole...</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>4109</th>
      <td>1646</td>
      <td>1</td>
      <td>Veggie Salad Bowl</td>
      <td>[Tomatillo Red Chili Salsa, [Fajita Vegetables...</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>738</th>
      <td>304</td>
      <td>1</td>
      <td>Veggie Soft Tacos</td>
      <td>[Tomatillo Red Chili Salsa, [Fajita Vegetables...</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>3889</th>
      <td>1559</td>
      <td>2</td>
      <td>Veggie Soft Tacos</td>
      <td>[Fresh Tomato Salsa (Mild), [Black Beans, Rice...</td>
      <td>16.98</td>
    </tr>
    <tr>
      <th>2384</th>
      <td>948</td>
      <td>1</td>
      <td>Veggie Soft Tacos</td>
      <td>[Roasted Chili Corn Salsa, [Fajita Vegetables,...</td>
      <td>8.75</td>
    </tr>
    <tr>
      <th>781</th>
      <td>322</td>
      <td>1</td>
      <td>Veggie Soft Tacos</td>
      <td>[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...</td>
      <td>8.75</td>
    </tr>
    <tr>
      <th>2851</th>
      <td>1132</td>
      <td>1</td>
      <td>Veggie Soft Tacos</td>
      <td>[Roasted Chili Corn Salsa (Medium), [Black Bea...</td>
      <td>8.49</td>
    </tr>
    <tr>
      <th>1699</th>
      <td>688</td>
      <td>1</td>
      <td>Veggie Soft Tacos</td>
      <td>[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>1395</th>
      <td>567</td>
      <td>1</td>
      <td>Veggie Soft Tacos</td>
      <td>[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...</td>
      <td>8.49</td>
    </tr>
  </tbody>
</table>
<p>4622 rows × 5 columns</p>
</div>

In [56]:
chipo_shorted_by_price = chipo.sort_values(by='item_price', ascending=False)
chipo_shorted_by_price.head(1)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>order_id</th>
      <th>quantity</th>
      <th>item_name</th>
      <th>choice_description</th>
      <th>item_price</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>3598</th>
      <td>1443</td>
      <td>15</td>
      <td>Chips and Fresh Tomato Salsa</td>
      <td>NaN</td>
      <td>44.25</td>
    </tr>
  </tbody>
</table>
</div>

In [62]:
chipo_filtered = chipo[chipo.item_name=='Veggie Salad Bowl']
chipo_filtered.shape[0]

18

In [66]:
chipo_filtered_1 = chipo[(chipo.item_name=='Canned Soda')]
chipo_filtered = chipo_filtered[chipo_filtered_1.quantity > 1]
chipo_filtered.shape[0]

20